name: flutter_project_base
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.3

  easy_localization: ^3.0.3

  flutter_bloc: ^8.1.3

  get_it: ^7.6.4
  injectable: ^2.3.0

  logger: ^2.0.2

  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.7

  cupertino_icons: ^1.0.6

  cool_alert: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  flutter_gen_runner: ^5.3.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/

